### ISSUE TITLE
can't configure apache2?

### ISSUE THREAD

**Issue by Nemesis77swe** [chaptergy/certbot-dns-njalla#3]
Im getting this error when I'm trying to get it to work with apache2.
![2022-01-15 14 38 38](https://user-images.githubusercontent.com/40662061/149623849-6115586c-30ab-4e30-a69d-5e09197e56cd.png)

`Certbot doesn't know how to automatically configure the web server on this system. However, it can still get a certificate for you. Please run "certbot certonly" to do so. You'll need to manually configure your web server to use the resulting certificate.`

 if I add --apache to the string it will say to many flags.,?

**Comment by chaptergy** [comment]
Are you sure this has to do with this njalla certbot plugin? Because the dns validation should be totally independent from the webserver management part. Maybe you just don't have `python3-certbot-apache` installed?

**Comment by Nemesis77swe** [comment]
>  `python3-certbot-apache` 

Are there different versions of certbot?
I've got the one described on certbots page..
the error text that I wrote is from certbot 
it's possible that I've placed the plugin faulty, I have no idea where to put it

**Comment by chaptergy** [comment]
Well, there are multiple ways to install certbot, via a package manager, via pip or via snap for example. I think certbot is currently mainly suggesting the snap package, so you're probably using that. As a quick note, there currently is no snap package of this plugin published, see https://github.com/chaptergy/certbot-dns-njalla/issues/2.  
But independent of how you installed certbot, there are multiple types of plugins certbot supports. There are e.g. DNS plugins, which `certbot-dns-njalla` is. It only provides the interface between certbot and your DNS provider, so DNS records can be automatically created and removed. There are also other plugins like the apache plugin, which as far as I know does things like refreshing the web server after a new certificate was issued and editing the config files to use the certificate. 

So you can either run `certbot certonly` instead of just `certbot` as the message suggests to just generate the certificates, or you will have to look up how to properly set up the apache plugin. I don't really know much about that. I would suggest the [Letsencrypt Community](https://community.letsencrypt.org/) instead.

**Comment by Nemesis77swe** [comment]
I c, well, I tried to add the --apache, because that's all that's required for certbot to know that it's apache2 running.  
however, when I'm running that command together with  your command, it says:

`certbot --apache -a dns-njalla --dns-njalla-credentials njalla.ini -d *.mysite.org
`

`Too many flags setting configurators/installers/authenticators 'dns-njalla' -> 'apache`

that's why I thought it had to do with your plugin

**Comment by chaptergy** [comment]
If you have a look at the [certbot documentation](https://eff-certbot.readthedocs.io/en/stable/using.html#combining-plugins) in order to generate a certificate using one plugin and install it using the other you would have to use the `-i` flag.  So instead of `--apache` you would have to use `-i apache`.

**Comment by Nemesis77swe** [comment]
> So instead of `--apache` you would have to use `-i apache`.

oh, my bad, I did read something about it, my Alzheimer's lite has struck again.

ok, may I ask one last thing, where do I put the plugin ? there where no instructions on GitHub.

**Comment by chaptergy** [comment]
I'm not sure what you mean by where to put it? If you have installed certbot via `pip` you just have to also install it via `pip`. If you have installed certbot via `snap` I don't think there is currently a way to use it. I have struggled with creating a snap package before, but did not succeed. See issue https://github.com/chaptergy/certbot-dns-njalla/issues/2.

**Comment by Nemesis77swe** [comment]
Yeah, I saw that issue, but didn't understand it.. 
I'll install certbot with pip instead of snap.. thx for the help!

**Comment by Nemesis77swe** [comment]
me again, now with njalla installed on **snap**, where should the **njalla.ini** be stored? eff directs you  to a page, and there isn't njalla available

**Comment by chaptergy** [comment]
Just as you normally would, store it anywhere and then provide the path to the file after the `--dns-njalla-credentials` flag.

**Comment by Nemesis77swe** [comment]
ehh, I'm so stupid! sorry!
